network:
  ethernets:
    enp3s0f0:
      dhcp4: false
    enp3s0f1:
      dhcp4: false
    enp4s0:
      addresses:
      - 192.168.1.35/24
      gateway4: 192.168.1.1
      nameservers:
        addresses:
        - 192.168.1.241
      routes:
        - to: 10.0.0.0/8
          via: 192.168.1.253
  version: 2
