#
# CRI
#
- name: Check existing downloaded cri-containerd-cni
  stat:
    path: "{{ download_dir }}/cri-containerd-cni-{{ containerd_ver }}-linux-amd64.tar.gz"
  register: regi_cri_containerd

- name: Downloading cri-containerd-cni
  get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_ver }}/cri-containerd-cni-{{ containerd_ver }}-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - regi_cri_containerd.stat.exists == False
