#
# nerdctl
#   https://github.com/containerd/nerdctl
#
- name: Check existing the downloaded netdctl
  stat:
    path: "{{ download_dir }}/nerdctl-{{ nerdctl_ver }}-linux-amd64.tar.gz"
  register: regi_nerdctl

- name: Downloading nerdctl-{{ nerdctl_ver }}-linux-amd64.tar.gz
  get_url:
    url: "https://github.com/containerd/nerdctl/releases/download/v{{ nerdctl_ver }}/nerdctl-{{ nerdctl_ver }}-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - regi_nerdctl.stat.exists == False
