#
# RUNC
#
- name: "Check extisting downloaded {{ download_dir }}/runc.amd64"
  stat:
    path: "{{ download_dir }}/runc.amd64"
  register: regi_runc

- name: "Downloading runc.amd64"
  get_url:
    url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - regi_runc.stat.exists == False
