- copy:
    src: "{{ r_k8s_binary }}/kubelet"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Configure the Kubelet
  copy:
    src: "{{ r_ca_home2 }}/{{ ansible_facts.hostname }}-key.pem"
    dest: /etc/kubernetes/pki
    owner: root
    group: root
    mode: '0600'
    #remote_src: yes
- copy:
    src: "{{ r_ca_home2 }}/{{ ansible_facts.hostname }}.pem"
    dest: /etc/kubernetes/pki    
    owner: root
    group: root
    mode: '0600'
    #remote_src: yes
- copy:
    src: "{{ r_ca_kubeconfig }}/{{ ansible_facts.hostname }}.kubeconfig"
    dest: /etc/kubernetes/node.conf
    owner: root
    group: root
    mode: '0600'
    #remote_src: yes
- copy: 
    src: "{{ r_ca_home2 }}/ca.pem"
    dest: /etc/kubernetes/pki
    owner: root
    group: root
    mode: '0600'
    #remote_src: yes
- template:
    src: kubelet-config.yaml
    dest: /etc/kubernetes/config
    owner: root
    group: root
    mode: '0644'
- template:
    src: kubelet.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- systemd:
    name: kubelet
    state: started
    daemon_reload: yes
    enabled: yes
