#
# RUNC
#
- name: Downloading runc
  stat:
    path: "{{ download_dir }}/runc.amd64"
  #when: ansible_facts.hostname is match(download_node)
  register: regi_runc

- get_url:
    url: "https://github.com/opencontainers/runc/releases/download/{{ runc_version }}/runc.amd64"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - regi_runc.stat.exists == False


