#
# 
#
- name: 01 Cephをノードへデプロイ
  command: ceph-deploy new mon1 mon2 mon3 node1 node2 node3 node4
  register: ceph_deploy_01
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_01 }}" dest="{{ log_dir }}/01-ceph-deploy.log"

#
# 完了待ち
#
- wait_for:
    timeout: 100

##
##  Cephモジュールのインストール
##
- name: 02 Cephモジュールのインストール
  command: ceph-deploy install --release {{ ceph_version }} mon1 mon2 mon3 node1 node2 node3 node4
  register: ceph_deploy_02
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_02 }}" dest="{{ log_dir }}/02-ceph-deploy.log"

##
## Cephモニターのデプロイ　ノードを指定
## 
- name: 03 モニターノード設定
  command: ceph-deploy mon create mon1 mon2 mon3
  register: ceph_deploy_03
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_03 }}" dest="{{ log_dir }}/03-ceph-deploy.log"

##
## Cephモニターのデプロイ　初期設定
##
- name: 04 モニター初期化
  command: ceph-deploy mon create-initial
  register: ceph_deploy_04
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_04 }}" dest="{{ log_dir }}/04-ceph-deploy.log"

#
# Cephキーの収集
#
- name: 05 キーの収集 gatherkeys 
  command: ceph-deploy gatherkeys mon1 mon2 mon3 node1 node2 node3 node4
  register: ceph_deploy_05
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_05 }}" dest="{{ log_dir }}/05-ceph-deploy.log"



##
## モニター管理ノードの設定
##
- name: 07 ceph-deploy admin 
  command: ceph-deploy admin mon1 mon2 mon3
  register: ceph_deploy_07
  with_items: nodes
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_07 }}" dest="{{ log_dir }}/07-ceph-deploy.log"

##
## マネージャーデーモン と メタデータサーバーの構成
##
- name: 08-ceph-deploy
  command: ceph-deploy mgr create mon1 mon2 mon3
  register: ceph_deploy_08
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_08 }}" dest="{{ log_dir }}/08-ceph-deploy.log"

- name: 09-ceph-deploy 
  command: ceph-deploy mds create mon1 mon2 mon3
  register: ceph_deploy_09
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_09 }}" dest="{{ log_dir }}/09-ceph-deploy.log"




##
## ストレージノードのセットアップ
##
- name: 06 ストレージノードのセットアップ ディスク1
  command: ceph-deploy osd create --data {{ device_name_1 }} {{ item }}
  register: "ceph_deploy_06"
  with_items: "{{ nodes }}"
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="ceph_deploy_06" dest="{{ log_dir }}/06-ceph-deploy.log"

- name: 07 ストレージノードのセットアップ ディスク1
  command: ceph-deploy osd create --data {{ device_name_2 }} {{ item }}
  register: "ceph_deploy_06"
  with_items: "{{ nodes }}"
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="ceph_deploy_06" dest="{{ log_dir }}/06-ceph-deploy.log"

##
## クラッシュルールの設定
##
- name: 08 クラッシュルールの設定
  command: ceph osd crush tunables default
  register: ceph_14
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_14 }}" dest="{{ log_dir }}/14-ceph.log"


#### 



###############################################
##
## オブジェクトゲートウェイの生成
##
- name: 10-ceph-deploy rgw 
  command: ceph-deploy rgw create mon1 mon2 mon3
  register: ceph_deploy_10
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_deploy_10 }}" dest="{{ log_dir }}/10-ceph-deploy.log"

##
## オブジェクトストレージのプール作成
##
- name: 11-ceph create pool for object storage
  command: ceph osd pool create obj_data 16
  register: ceph_11
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_11 }}" dest="{{ log_dir }}/11-ceph.log"

##
## プールをマップ
##
- name: 12-ceph osd map 
  command: ceph osd map obj_data obj01
  register: ceph_12
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_12 }}" dest="{{ log_dir }}/12-ceph.log"




###############################################
##
## ブロック・ストレージのプール作成
##
- name: 13-ceph create pool for block storage
  command: ceph osd pool create blk_data 16
  register: ceph_13
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_13 }}" dest="{{ log_dir }}/13-ceph.log"


##
## ブロック・ストレージのプールのアプリを設定する
##
- name: 13.5-ceph create pool for block storage
  command: ceph osd pool application enable blk_data rbd
  register: ceph_13_5
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_13_5 }}" dest="{{ log_dir }}/13.5-ceph.log"

##
## CSI用ブロック・ストレージのプール作成
##
- name: 13-ceph create pool for block storage kubernetes
  command: ceph osd pool create kubernetes 16
  register: ceph_13
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_13 }}" dest="{{ log_dir }}/13-ceph.log"


##
## CSI用ブロック・ストレージのプール作成
##
- name: 13-ceph create pool for block storage
  command: rbd pool init kubernetes
  register: ceph_13
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_13 }}" dest="{{ log_dir }}/13-ceph.log"

##
## CSIでアクセスするユーザーの作成と権限設定
##
- name: 13-ceph create pool for block storage
  command: ceph auth get-or-create client.kubernetes mon 'profile rbd' osd 'profile rbd pool=kubernetes' mgr 'profile rbd pool=kubernetes'
  register: ceph_13
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_13 }}" dest="{{ log_dir }}/13-ceph.log"





###############################################
##
## ファイルストレージの設定
##
- name: 15-cpeh create pool for file storage
  command: ceph osd pool create cephfs_data 16
  register: ceph_15
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_15 }}" dest="{{ log_dir }}/15-ceph.log"

- name: 16-ceph create pool fs metadata
  command: ceph osd pool create cephfs_metadata 4
  register: ceph_16
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_16 }}" dest="{{ log_dir }}/16-ceph.log"

- name: 17-ceph fs new cephfs 
  command: ceph fs new cephfs cephfs_metadata cephfs_data
  register: ceph_17
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_17 }}" dest="{{ log_dir }}/17-ceph.log"

##
## Cephユーザーの作成
## https://github.com/ceph/ceph-csi/blob/devel/docs/capabilities.md#cephfs
##
- name: 17-1-ceph create user
  #command: ceph auth get-or-create client.cephfs mon 'allow r' osd 'allow rw tag cephfs metadata=*' mgr 'allow rw'
  command: ceph auth get-or-create client.cephfs mon 'allow r' osd 'allow rw tag cephfs *=*' mgr 'allow rw' mds 'allow rw'
  register: ceph_17
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_17 }}" dest="{{ log_dir }}/17-ceph.log"

- name: 17-2-ceph create user
  command: ceph fs authorize cephfs client.cephfs2 / rw
  register: ceph_17
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_17 }}" dest="{{ log_dir }}/17-ceph.log"


##
## ダッシュボードの設定
##
- name: 18-ceph mgr module enable dashboard
  command: ceph mgr module enable dashboard
  register: ceph_18
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_18 }}" dest="{{ log_dir }}/18-ceph.log"

- name: 19-ceph Create self-signed certificate
  command: ceph dashboard create-self-signed-cert
  register: ceph_19
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_19 }}" dest="{{ log_dir }}/19-ceph.log"

- name: 20-ceph put password file
  template:
    src:  ceph-rds-password
    dest: /root/ceph-rds-password
    mode: '0644'
    owner: root
    group: root

- name: 21-ceph Set user/password & role
  command: ceph dashboard ac-user-create admin -i /root/ceph-rds-password administrator
  register: ceph_21
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_21 }}" dest="{{ log_dir }}/21-ceph.log"


##
## auth_allow_insecure_global_id_reclaim
##
- name: 22-ceph auth_allow_insecure_global_id_reclaim
  command: ceph config set mon auth_allow_insecure_global_id_reclaim false
  register: ceph_22
  args:
    chdir: "{{ cadmin_home }}"
- local_action: copy content="{{ ceph_22 }}" dest="{{ log_dir }}/22-ceph.log"

