#
# Front Proxy の設定
#
- name: Create Front-Proxy CA working directory
  file:
    path: "{{ ca_front_proxy }}"
    state: directory
    owner: root
    group: root

#
# Front Proxy CAの作成
#
- name: Create Front-Proxy CA
  template:  
    src: front-proxy-ca-config.json
    dest: "{{ ca_front_proxy }}"
    owner: root
    group: root
    mode: '0644'
- template:
    src: front-proxy-ca-csr.json
    dest: "{{ ca_front_proxy }}"
    owner: root
    group: root
    mode: '0644'
- name: check existing front-proxy-ca.pem
  stat:
    path: "{{ ca_front_proxy }}/front-proxy-ca.pem"
  register: file_front_proxy_ca
- shell: |
    cfssl gencert -initca front-proxy-ca-csr.json | cfssljson -bare front-proxy-ca
  args:
    chdir: "{{ ca_front_proxy }}"
  when: file_front_proxy_ca.stat.exists == False
    
- name: Front-proxy Client Certificate
  template:
    src: front-proxy-client-csr.json
    dest: "{{ ca_front_proxy }}"
    owner: root
    group: root
    mode: '0644'
- name: check existing front-proxy-client.pem
  stat:
    path: "{{ ca_front_proxy }}/front-proxy-client.pem"
  register: file_front_proxy_client
    
- shell: |
    cfssl gencert \
      -ca=front-proxy-ca.pem \
      -ca-key=front-proxy-ca-key.pem \
      -config=front-proxy-ca-config.json \
      -profile=kubernetes \
    front-proxy-client-csr.json | cfssljson -bare front-proxy-client
  args:
    chdir: "{{ ca_front_proxy }}"
  when: file_front_proxy_client.stat.exists == False


- name: chmod 0644 front-proxy-ca-key.pem
  file:
    path: "{{ ca_front_proxy }}/front-proxy-ca-key.pem"
    owner: root
    group: root
    mode: '0644'

- name: chmod 0644 front-proxy-client-key.pem
  file:
    path: "{{ ca_front_proxy }}/front-proxy-client-key.pem"
    owner: root
    group: root
    mode: '0644'

