#
# CRI
#
- name: Downloading cri-containerd
  stat:
    path: "{{ download_dir }}/cri-containerd-cni-{{ containerd_version }}-linux-amd64.tar.gz"
  register: regi_cri_containerd

- get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/cri-containerd-cni-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - regi_cri_containerd.stat.exists == False



