#
# Containerd のダウンロードとインストール
#

#
# これはmasterやworkerで実行されるため、NFSのディレクトリ{{ r_download_dir }}から展開する
#

#
# mkdir directory for cni
#  flannel などのプラグインの設定ファイルが入る
#
- name: start configuration
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- template:
    src: 01-marmot.conflist
    dest: /etc/cni/net.d
    owner: root
    group: root
    mode: '0644'


- name: mkdir /opt/cni/bin/
  file:
    path: /opt/cni/bin/
    state: directory
    owner: root
    group: root
    mode: '0755'
  
- name: Configure CNI Networking
  unarchive:
    src: "{{ download_dir }}/cni-plugins-linux-amd64-{{ cni_plugins }}.tgz"
    dest: /opt/cni/bin/
    remote_src: True
    owner: root
    group: root
    mode: '0755'

- name: install containerd 1.3 upper
  unarchive:
    src: "{{ download_dir }}/containerd-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: /usr/local
    remote_src: True
    owner: root
    group: root
    mode: '0755'


- name: install crictl
  unarchive:
    src: "{{ download_dir }}/crictl-{{ crictl_version }}-linux-amd64.tar.gz"
    dest: /usr/local/bin/
    remote_src: True
    owner: root
    group: root
    mode: '0755'

- template:
    src: crictl.yaml
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: '0644'

- copy:
    src: "{{ download_dir }}/runc.amd64"
    dest: /usr/local/bin/runc
    remote_src: True
    owner: root
    group: root
    mode: '0755'

- name: Configure containerd
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

#
# メモリ不足時に、OOMでカーネルからキルされないため
#
- template:
    src:  config.toml-oom.j2
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'


###
# Harbor の自己署名証明書をチェックする場合
# templatesにファイルをセットして、以下のコメントを外す
# 前述のconfig.toml.j2では、対象ファイル部分がコメントになっているので変更する。
#
- name: Download CA pem
  get_url:
    url: "https://{{ public_ip_dns }}/ca.pem"
    dest: /etc/containerd/ca.crt
    validate_certs: no
    mode: 0440

- name: Download harbor cert pem
  get_url:
    url: "https://{{ public_ip_dns }}/harbor.labo.local/harbor.labo.local.crt"
    dest: /etc/containerd/harbor.labo.local.crt
    validate_certs: no
    mode: 0440

- name: Download harbor key pem
  get_url:
    url: "https://{{ public_ip_dns }}/harbor.labo.local/harbor.labo.local.key"
    dest: /etc/containerd/harbor.labo.local.key
    validate_certs: no
    mode: 0440

- template:
    src: containerd.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Start the Worker Services
  systemd:
    name: containerd  
    state: started
    daemon_reload: yes
    enabled: yes



