apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-tkr
  namespace: elasticsearch
spec:
  version: 8.4.1
  nodeSets:
  - name: default
    count: 1
    config:
      #node.roles: ["master", "data", "ingest", "ml"]    
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          apl: elastic
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        storageClassName: csi-rbd-sc
  transport:
    service:
      metadata:
        labels:
          my-custom: k8s1-ka
      spec:
        type: LoadBalancer
