##
## Configure the Kubernetes Controller Manager
##

- name: copy kube-controller-manager bin
  copy:
    src: "{{ r_k8s_binary }}/kube-controller-manager"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

- name: Configure the Kubernetes Controller Manager
  copy:
    src: "{{ r_ca_kubeconfig }}/kube-controller-manager.kubeconfig"
    dest: /etc/kubernetes/controller-manager.conf
    owner: root
    group: root
    mode: '0644'
- template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    owner: root
    group: root
    mode: '0644'
  when:
    - kubernetes_version is version('1.20.0', '<')

- name: copy  kube-apiserver.service
  template:
    src: kube-controller-manager.service-v1.20.j2
    dest: /etc/systemd/system/kube-controller-manager.service
    owner: root
    group: root
    mode: '0644'
  when:
    - kubernetes_version is version('1.20.0', '>')
