##
## Configure the Kubernetes Scheduler
##
- name: Copy Scheduler bin
  copy:
    src: "{{ r_k8s_binary }}/kube-scheduler"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    remote_src: yes

##
## スケジューラーの証明書を配置
##
- name: Configure the Kubernetes Scheduler
  copy:
    src: "{{ r_ca_kubeconfig }}/kube-scheduler.kubeconfig"
    dest: /etc/kubernetes/kube-scheduler.conf
    owner: root
    group: root
    mode: '0644'


##
## スケジューラーのコンフィグを配置
##
- template:
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/config
    owner: root
    group: root
    mode: '0644'
  when:
    - kubernetes_version is version('1.19.0', '<')

- template:
    src: kube-scheduler.yaml.k8s-1.19
    dest: /etc/kubernetes/config/kube-scheduler.yaml
    owner: root
    group: root
    mode: '0644'
  when:
    - kubernetes_version is version('1.19.0', '>=')
    

##
## kube-schedulerをsystemdから起動するためのファイルを配置
##
- template:
    src: kube-scheduler.service.j2
    dest: /etc/systemd/system/kube-scheduler.service
    owner: root
    group: root
    mode: '0644'

