##
## Enable HTTP Health Checks
##
- name: Enable HTTP Health Checks
  apt:
    name: nginx
    state: present
- template:
    src: kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-available
- file:
    src: /etc/nginx/sites-available/kubernetes.default.svc.cluster.local
    dest: /etc/nginx/sites-enabled/kubernetes.default.svc.cluster.local
    state: link
- systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
