#- include_vars: /vagrant/playbook/vars/main.yaml
#
# ブリッジ設定でポッドネットワークを構築する
#
- name: deploy /etc/cni/net.d/10-bridge.conf
  template:
    src: "10-bridge.conf.{{ ansible_facts.hostname }}"
    dest: /etc/cni/net.d/10-bridge.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_facts.hostname is not match("master[123]") or {{ single_node }} == True
  # シングル ノードクラスタの時はコメントにする

- debug: msg="single_node == {{ single_node }}"
  
- name: static route masters
  include_tasks: static-route.yaml
  when: ansible_facts.hostname is match("master[123]") or {{ single_node }} == True
  # シングル ノードクラスタの時はコメントにする
  
- name: static route for each node
  include_tasks: "static-route-{{ ansible_facts.hostname }}.yaml"
  when: ansible_facts.hostname is not match("master[123]") or {{ single_node }} == True
  # シングル ノードクラスタの時はコメントにする


