#
# server for code development
#
domain: labo.local
os_variant:  ubuntu20.04

cluster_name: dev
vm_spec:
  - name: "dev-server"
    cpu: 2
    memory: 4096
    private_ip: "172.16.99.11"
    storage:
    - name: /dev/vdb
      size: 100
      vg:   vg1
    playbook: install.yaml
    comment: "Test node #1"
