#
# Config Etcd 
#
- name: Setup environment for etcd
  file:
    path: /etc/kubernetes/pki/etcd
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /var/lib/etcd
    state: directory
    owner: root
    group: root
    mode: '0755'
- copy:
    src:  "{{ r_download_dir }}/etcd-{{ etcd_version }}-linux-amd64/etcd"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
- copy:
    src:  "{{ r_download_dir }}/etcd-{{ etcd_version }}-linux-amd64/etcdctl"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
- copy:
    src: "{{ r_ca_home2 }}/ca.pem"
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-ca.pem"
    dest: /etc/kubernetes/pki/etcd/ca.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-ca-key.pem"
    dest: /etc/kubernetes/pki/etcd/ca.key
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-server.pem"
    dest: /etc/kubernetes/pki/etcd/server.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-server-key.pem"
    dest: /etc/kubernetes/pki/etcd/server.key
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-peer.pem"
    dest: /etc/kubernetes/pki/etcd/peer.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_etcd_home }}/etcd-peer-key.pem"
    dest: /etc/kubernetes/pki/etcd/peer.key
    owner: root
    group: root
    mode: '0600'

#########    
- name: Copy ETCD CA Cert
  copy:
    src: "{{ r_ca_home2 }}/kubernetes.pem"
    dest: /etc/kubernetes/pki/apiserver-etcd-client.crt
    owner: root
    group: root
    mode: '0600'
- copy:
    src: "{{ r_ca_home2 }}/kubernetes-key.pem"
    dest: /etc/kubernetes/pki/apiserver-etcd-client.key
    owner: root
    group: root
    mode: '0600'

###########    
#  Interface name is changed depend on Hypervisor.
#  it should not use in the template file.
#  like this  ansible_facts.enp0s8.ipv4.address 
###########
- debug: msg="{{ ansible_facts.virtualization_type }}"
- debug: msg="{{ internal_ipv4_address }}"


- template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    owner: root
    group: root
    mode: '0644'

- debug: msg="{{ ansible_facts.hostname }}"

- name: Start etcd service
  systemd:
    name: etcd.service
    state: started
    daemon_reload: yes
    enabled: yes

    
