##
## Prometheus Operator によるメトリックス監視
##   名前空間 monitoringにPrometheus,Grafana,kube-state-metricsをインストールする
##   ストレージは、デフォルトでEmptyDir を使う。
## 


##
## Install Prometheus Oprator
##
- name: check kube-prometheus
  stat:
    path: "{{ cadmin_home }}/kube-prometheus/README.md"
  register: regi_prometheus

- name: git clone kube-prometheus
  become_user: "{{ cluster_admin }}"
  git:
    repo: 'https://github.com/prometheus-operator/kube-prometheus'
    version: release-0.10
    dest: "{{ cadmin_home }}/kube-prometheus"
  when: regi_prometheus.stat.exists == False

- name: deploy kube-prometheus
  become_user: "{{ cluster_admin }}"
  shell: |
        kubectl apply --server-side -f manifests/setup
        kubectl apply -f manifests/
  args:
    chdir: "{{ cadmin_home }}/kube-prometheus"



  
