#
#  コントローラー抜きでポッドを起動
#
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: harbor.labo.local/x/nginx:latest
    imagePullPolicy: Always
  imagePullSecrets:
  - name: regcred