#
# KeepAlivedソースコードをダウンロード
#
- name: Downloading keepalived
  stat:
    path: "{{ download_dir }}/keepalived-{{ keepalived_version }}.tar.gz"
  register: regi_keepalived

- get_url:
    url: "https://www.keepalived.org/software/keepalived-{{ keepalived_version }}.tar.gz"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - regi_keepalived.stat.exists == False


#
# ソースコードを展開
#
- name: extracted  keepalived
  stat:
    path: "{{ download_dir }}/keepalived-{{ keepalived_version }}/README.md"
  register: regi_keepalived_extra

- unarchive:
    src: "{{ download_dir }}/keepalived-{{ keepalived_version }}.tar.gz"
    dest: "{{ download_dir }}"
    remote_src: True
  when:
    - regi_keepalived_extra.stat.exists == False


#
# ビルド
#
- name: Build keepalived
  shell: |
    ./configure
    make
  args:
    chdir: "{{ download_dir }}/keepalived-{{ keepalived_version }}"


