#
# Keepalivedのインストール
#
- shell: |
      make install
  args:
    chdir: "{{ download_dir }}/keepalived-{{ keepalived_version }}"

#
# 起動停止のSystemd設定
#
- name: deploy keepalived service
  template:
    src: keepalived.service.j2
    dest: /etc/systemd/system/keepalived.service
    owner: root
    group: root
    mode: '0644'

- name: /etc/keepalived/keepalived.conf to master mlb
  file:
    path: /etc/keepalived
    state: directory
    owner: root
    group: root
    mode: '0755'


#########################################################
#
# 内部ロードバランサーへ導入（ホスト名で判定）
#
- name: /etc/keepalived/keepalived.conf to primary mlb
  template:
    src: keepalived.conf.master.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts.hostname is match("mlb1")
    - lb_pos == "Internal"

- name: /etc/keepalived/keepalived.conf to backup mlb
  template:
    src: keepalived.conf.backup.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts.hostname is match("mlb2")
    - lb_pos == "Internal"


#
# 外部ロードバランサーへ導入（ホスト名で判定）
#
- name: /etc/keepalived/keepalived.conf to primary elb
  template:
    src: keepalived.conf.master_frontend.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts.hostname is match("elb1")
    - lb_pos == "Frontend"

- name: /etc/keepalived/keepalived.conf to backup elb
  template:
    src: keepalived.conf.backup_frontend.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  when:
    - ansible_facts.hostname is match("elb2")
    - lb_pos == "Frontend"


#
# プライマリ／バックアップ切り替わり時のシェルデプロイ
#
- name: copy /etc/keepalived/master.sh
  template:
    src: master.sh
    dest: /etc/keepalived/master.sh
    owner: root
    group: root
    mode: '0700'
  when:
    - ansible_facts.hostname is match("elb[12]")
    - lb_pos == "Frontend"

- name: copy /etc/keepalived/backup.sh
  template:
    src: backup.sh
    dest: /etc/keepalived/backup.sh
    owner: root
    group: root
    mode: '0700'
  when:
    - ansible_facts.hostname is match("elb[12]")
    - lb_pos == "Frontend"


#
# Keepalivedの起動
#
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable and start a keepalived
  systemd:
    name: keepalived
    state: started
    enabled: yes






