#
# server for code development
#
domain: labo.local
os_variant:  ubuntu22.04

cluster_name: dev
vm_spec:
  - name: "ci-runner"
    cpu: 2
    memory: 4096
    private_ip: "172.16.0.20"
    storage:
    - name: /dev/vdb
      size: 100
      vg:   vg1
    - name: /dev/vdc
      size: 100
      vg:   vg1
    - name: /dev/vdd
      size: 100
      vg:   vg2
    #- name: /dev/vde
    #  size: 100
    #  vg:   vg3
    playbook: install.yaml
    comment: "Test node #1"
