#
# server for code development
#
domain: labo.local
os_variant:  ubuntu22.04

cluster_name: dev
vm_spec:
  - name: "hvc"
    cpu: 4
    memory: 16384
    private_ip: "172.16.0.20"
    public_ip:  "192.168.1.220"
    storage:
    - name: /dev/vdb
      size: 100
      vg:   vg1
    - name: /dev/vdc
      size: 100
      vg:   vg1
    - name: /dev/vdd
      size: 100
      vg:   vg2
    #- name: /dev/vde
    #  size: 100
    #  vg:   vg3
    playbook: install.yaml
    comment: "Test node #1"
