- name: install controller
  hosts: control
  become: true
  #gather_facts: yes
  vars:
    cluster_admin:  "ubuntu"
    mail_domain:    "labo.local"
    fqdn:           "jenkins.labo.local"
    domain:         "{{ fqdn }}"
    disk1:          "/dev/vdb"
    path1:          "/var/lib/jenkins"
    disk2:          "/dev/vdc"
    #dst_dir:       "/etc/apache2/ssl"
    web_cert:       "/etc/apache2/ssl"
    #home_path:     "/var/lib/jenkins/.ssh"
    jenkins_ssh:    "/var/lib/jenkins/.ssh"
    root_ssh:       "/root/.ssh"



- name: copy from control
  hosts: control
  become: true
  tasks:
    - name: copy file from control to local
      fetch: src=/root/.ssh/id_rsa.pub dest=/tmp/id_rsa.pub

- name: copy to build
  hosts: build1
  become: true
  tasks:
    - name: copy file from local to build1
      copy: src=/tmp/id_rsa.pub/control/root/.ssh/id_rsa.pub dest=/root/.ssh/id_rsa.pub

    - name: concat pub-key and authorized_keys
      shell: cat id_rsa.pub >> authorized_keys
      args:
        chdir: /root/.ssh
