- name: basic information
  hosts: all
  gather_facts: true
  become: true

  vars:
    cluster_admin: ubuntu
    admin_user:    ubuntu
    mail_domain:   "labo.local"
    my_host:       "harbor"
    fqdn:          "{{ my_host }}.labo.local"
    my_data:       /harbor
    dst_dir:       /harbor/certs
    disk_sdc:      "{{ my_data }}"
    harbor_ver:    "v2.4.2"

  tasks:
  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  roles:
    - base_linux
    - mail-client
    - docker
    - vdisks
    - download_certs

  tasks:
  #- debug: msg="{{ ansible_facts.enp0s9.ipv4.address }}"

  - name: Download the Harbor Installer
    shell: |
      gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys 644FF454C0B4115C
      curl -O -L https://github.com/goharbor/harbor/releases/download/{{ harbor_ver }}/harbor-online-installer-{{ harbor_ver }}.tgz
      curl -O -L https://github.com/goharbor/harbor/releases/download/{{ harbor_ver }}/harbor-online-installer-{{ harbor_ver }}.tgz.asc
      gpg -v –keyserver hkps://keyserver.ubuntu.com –verify harbor-online-installer-{{ harbor_ver }}.tgz.asc
      tar xzvf harbor-online-installer-{{ harbor_ver }}.tgz
    args:
      chdir: /harbor

  - name: Configure HTTPS Access to Harbor
    file:
      path: /harbor/certs
      state: directory

  - name: copy harbor.yml
    template:
      src: harbor.yml.j2
      dest: /harbor/harbor/harbor.yml

  - name: Run the Installer Script
    shell: |
      ./install.sh
    args:
      chdir: /harbor/harbor

  - name: Wait for Start
    shell: |
      sleep 60
    args:
      chdir: /harbor/harbor

  - name: Stop Harbor
    shell: |
       docker-compose down
    args:
      chdir: /harbor/harbor

  - name: Setup as service
    template:
      src: docker-compose.service.j2
      dest: /etc/systemd/system/harbor.service

  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: harbor

  - name: copy backup shell script
    ansible.builtin.copy:
      src: backup.sh
      dest: /usr/local/bin
      owner: root
      group: root
      mode: '0750'

  - name: copy restore shell script
    ansible.builtin.copy:
      src: restore_latest.sh
      dest: /usr/local/bin
      owner: root
      group: root
      mode: '0750'

