#- debug: msg="{{ ansible_facts }}"

##
## Ubuntu の 自動アップデートを禁止する
##
- replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: 'APT::Periodic::Update-Package-Lists "1";'
    replace: 'APT::Periodic::Update-Package-Lists "0";'
    backup: no

##
## 管理ユーザーをrootグループへ追加
##
- name: admin  user add root group
  user:
    name: "{{ cluster_admin }}"
    groups: root
    append: yes


- name: update ca certs etc
  shell: |
    apt install ca-certificates
    apt update -y

##
## パッケージの追加
##
- name: Install Ubuntu package
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nfs-common
    - nfs-client
    - ruby
    - emacs-nox
    - rsync



- name: Ensure group 'admin' exists
  group:
    name:  "{{ cluster_admin }}"
    state: present


- name: Add the user 'admin' with a bash shell,
  user:
    name:  "{{ cluster_admin }}"
    shell: /bin/bash
    group: "{{ cluster_admin }}"

- name: add sudoers
  template:
    src:  sudor.j2
    dest: "/etc/sudoers.d/{{ cluster_admin }}"
    owner: root
    group: root
    mode: '0440'

- name: copy hosts
  template:
    src:  hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'


- debug: msg="{{ ansible_facts.virtualization_type }}"
##
## sshkey sharing
##
- name: SSH-KEY FOR KVM VM
  include_tasks: sshkey-sharing-kvm.yaml
  when: ansible_facts.virtualization_type == "kvm"


#
# DNSの設定を変更
#
- name: set systemd-resolved config
  template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    owner: root
    group: root
    mode: '0644'

#
# シンボリックリング /etc/resolv.conf を変更
#
- name: change symbolic link for /etc/resolv.conf
  shell: |
    ln -sf ../run/systemd/resolve/resolv.conf resolv.conf
  args:
    chdir: /etc

#
# リスタート　systemctl restart systemd-resolved
#
- systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes
    enabled: yes

#
# NFS
#
- name: Mount NFS
  include_tasks: nfs-mount.yaml
