#
# 最小構成のサーバー
#
domain: labo.local
cluster_name: infra
os_variant:  ubuntu22.04

vm_spec:
  - name: "server-pv"
    cpu: 2
    memory: 4096
    private_ip:  "172.16.20.4"
    public_ip:   "192.168.1.179"
    storage:
    - name: /dev/vdb
      size: 2
      vg:   vg1
    - name: /dev/vdc
      size: 2
      vg:   vg1
    - name: /dev/vdd
      size: 2
      vg:   vg1
    - name: /dev/vde
      size: 2
      vg:   vg1
    comment: "First Simple Server"

