#
# Kubernetesクラスタの構成
#

domain: labo.local
os_variant:  ubuntu20.04
cluster_name: k8s3

vm_spec:
  - name: "elb1"
    cpu: 1
    memory: 2048
    private_ip: "172.16.3.11"
    public_ip:  "192.168.1.180"
    storage:
    - name: data
      size: 8
      vg:   vg2
    playbook: install.yaml
    comment:  "Load Balancer #1"

  - name: "master1"
    cpu: 2
    memory: 4096
    private_ip: "172.16.3.21"
    #public_ip:  "192.168.1.181"
    storage:
    - name: container-fs
      size: 20
      vg:   vg2
    playbook: install.yaml
    comment:  "Master node #1"

  - name: "node1"
    cpu: 2
    memory: 8196
    private_ip: "172.16.3.31"
    storage:
    - name: container-fs
      size: 20
      vg:   vg2
    playbook: install.yaml
    comment:  "Worker node #1"

  - name: "node2"
    cpu: 2
    memory: 8196
    private_ip: "172.16.3.32"
    storage:
    - name: container-fs
      size: 20
      vg:   vg2
    playbook: install.yaml
    comment:  "Worker node #2"


