source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'yaml'
#gem 'json', '~> 2.3.1'
gem 'mb_string'
gem 'net-ping', '~> 2.0', '>= 2.0.8'
gem 'etcdv3'
