---
apiVersion: v1
kind: Pod
metadata:
  name: test-cephfs-2
spec:
  containers:
    - name: my-ubuntu
      image: maho/my-ubuntu:0.1
      command: ["tail", "-f", "/dev/null"]      
      volumeMounts:
        - name: mypvc
          mountPath: /mnt
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: cephfs-pvc
        readOnly: false
