---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: cephfs
  userKey: AQDOZTBiqWYlNxAAh+iPDdXGHFX7l+nVBQWGCA==

  # Required for dynamically provisioned volumes
  adminID: cephfs
  adminKey: AQDOZTBiqWYlNxAAh+iPDdXGHFX7l+nVBQWGCA==
