#
# Kubernetesクラスタ構成ファイル
#
### VM Host network interfaice
#bridge_if: "en0: Wi-Fi (Wireless)"
bridge_if: "eno1"

## Hypervisor type
##  kvm : CentOS8 virsh
##  vv  : VirtualBox + Vagrant
hypervisor: kvm
#hypervisor: vv

### Container Runtime
container_runtime:  containerd
containerd_version: "1.2.13"
#
#container_runtime:  docker
#docker_version:     "5:18.09.9~3-0~ubuntu-bionic"
#
#container_runtime:  cri-o
#crio_version:       "1.17"
#
crictl_version:     "v1.15.0"

### K8s cluster/pod network CNI plugin
cni_plugins:        "v0.8.2"
#pod_network: bridge
#
#pod_network: flannel
#flannel_version: v0.12.0
#
pod_network: calico
calico_version: v3.14.1


### Kubernetes version
kubernetes_version: 1.18.10
kubernetes_custom: False
kubernetes_dashborad_ver: v2.0.0



### Cluster Network
private_ip_subnet: 172.16.20.0/24
public_ip_subnet:  192.168.1.0/24


### Load Balancer config
keepalived_version: 2.0.15

### Internal Load Balancer
kube_apiserver_vip: 172.16.20.53
ka_primary_internal_host: mlb1
ka_backup_internal_host: mlb2

### Frontend Load Balancer
front_proxy_vip: 192.168.1.63
istio_gateway_vip: 192.168.1.64
ka_primary_frontend_host: elb1
ka_backup_frontend_host: elb2


### extra addons
sw_rook_ceph:    True
sw_promethus:    True
sw_grafana:      True
sw_elk:          True
sw_istio:        True
sw_knative:      True
sw_container_fs: True


### DOMAIN
domain: labs.local

### Master, Worker, Internal/Frontend Loadbalancer and bootnode
vm_spec:
  - name: "master1"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.41"
    public_ip: "192.168.1.41"
    storage:
    - 16
    playbook: "setup_linux.yaml"
    comment: "Master node #1"
    
  - name: "master2"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.42"
    public_ip: "192.168.1.42"
    storage:
    - 16
    playbook: "setup_linux.yaml"
    comment: "Master node #2"
    
  - name: "master3"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.43"
    public_ip: "192.168.1.43"
    storage:
    - 16      
    playbook: "setup_linux.yaml"
    comment: "Master node #3"
  
  - name: "mlb1"
    cpu: 1
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.51"
    public_ip: "192.168.1.51"
    storage:
    playbook: "setup_linux.yaml"
    comment: "Internal Master Loadbalancer #1"

  - name: "mlb2"
    cpu: 1
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.52"
    public_ip: "192.168.1.52"
    storage:
    playbook: "setup_linux.yaml"
    comment: "Internal Master Loadbalancer #2"

  - name: "elb1"
    cpu: 1
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.61"
    public_ip: "192.168.1.61"
    storage:
    - 8
    role: "proxy"      
    playbook: "setup_linux.yaml"
    comment: "Frontend Master Loadbalancer #1"

  - name: "elb2"
    cpu: 1
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.62"
    public_ip: "192.168.1.62"
    storage:
    - 8
    role: "proxy"      
    playbook: "setup_linux.yaml"
    comment: "Frontend Backup Loadbalancer #2"


  - name: "node1"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.71"
    public_ip: "192.168.1.71"    
    storage:
    - 16
    playbook: "setup_linux.yaml"
    role: "worker"
    comment:  "Worker node #1"
    
  - name: "node2"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.72"
    public_ip: "192.168.1.72"
    storage:
    - 16
    playbook: "setup_linux.yaml"
    role: "worker"    
    comment: "Worker node #2"
    
  - name: "node3"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.73"
    public_ip: "192.168.1.73"
    storage:
    - 16
    playbook: "setup_linux.yaml"
    role: "worker"
    comment: "Worker node #3"

  - name: "node4"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.74"
    public_ip: "192.168.1.74"
    storage:
    - 16
    playbook: "setup_linux.yaml"
    role: "worker"
    comment: "Worker node #4"

  - name: "storage1"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.81"
    public_ip: "192.168.1.81"
    storage:
    - 16
    - 80
    playbook: "setup_linux.yaml"
    role: "storage"
    node_label:
    - app: rook-ceph-mds
    comment: "Storage node #1"

  - name: "storage2"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.82"
    public_ip: "192.168.1.82"
    storage:
    - 16
    - 80
    playbook: "setup_linux.yaml"
    role: "storage"
    node_label:
    - app: rook-ceph-mds
    comment: "Storage node #2"

  - name: "storage3"
    cpu: 2
    memory: 8192
    box: "ubuntu/bionic64"
    private_ip: "172.16.20.83"
    public_ip: "192.168.1.83"
    storage:
    - 16
    - 80
    playbook: "setup_linux.yaml"
    role: "storage" 
    node_label:
    - app: rook-ceph-mds
    comment: "Storage node #3"

  - name: "bootnode"
    cpu: 2
    memory: 2048
    private_ip: "172.16.20.40"
    public_ip: "192.168.1.40"    
    box: "ubuntu/bionic64"
    playbook: "setup_linux.yaml"    
    comment: "Bootstap node" 

    
