#
# 最小構成のK8sクラスタ
#

domain: labs.local

### host network interfaice
bridge_if: "en0: Wi-Fi (Wireless)"
#bridge_if: "eno1"

## Hypervisor type
##  kvm : CentOS8 virsh
##  vv  : VirtualBox + Vagrant
#hypervisor: kvm
hypervisor: vv


### Kubernetes version
kubernetes_version: 1.18.2
kubernetes_custom: False
#kubernetes_custom: True


### K8s cluster/pod network CNI plugin
#pod_network: bridge
pod_network: flannel

### flannel_version if you choice flannel
flannel_version: v0.12.0

### Cluster Network
private_ip_subnet: 172.16.10.0/24
public_ip_subnet:  192.168.1.0/24

## マスターか内部LBのIPをセットする
kube_apiserver_vip: 172.16.1.41


### Virtual Machine Spec
vm_spec:
  - name: "master1"
    cpu: 2
    memory: 2048
    box: "ubuntu/bionic64"
    private_ip: "172.16.10.41"
    public_ip: "192.168.1.41"    
    storage:
    playbook: "setup_linux.yaml"
    comment: "Master node #1"
    
  - name: "node1"
    cpu: 1
    memory: 1024
    box: "ubuntu/bionic64"
    private_ip: "172.16.1.71"
    storage:
    playbook: "setup_linux.yaml"
    pod_network: "10.244.1.0/24"
    role: "worker"
    comment:  "Worker node #1"

  - name: "bootnode"
    cpu: 1
    memory: 1024
    box: "ubuntu/bionic64"    
    private_ip: "172.16.1.40"
    playbook: "setup_linux.yaml"
    comment: "Bootstap node" 

    
