# Master と Workerで共通のタスク
#- debug: msg="{{ ansible_facts }}"

##  Docker のインストール
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce{{ docker_version_ubuntu }}

- name: docker config
  template:
    src: docker.service
    dest: /lib/systemd/system/docker.service
    owner: root
    group: root
    mode: '0644'

- name: Add the user {{ admin_user }} with a specific uid and a primary group of 'docker'
  user:
    name: "{{ admin_user }}"
    comment: docker exection user
    group: docker

- name: Set sysctl 
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    sysctl_set: yes
    sysctl_file: /etc/sysctl.conf      
    state: present
    reload: yes

- name: chmod 0666 /var/run/docker.sock
  file:
    path: "/var/run/docker.sock"
    owner: root
    group: root
    mode: '0666'

########

- name: mkdir dest dir
  file:
    path:  "/etc/docker/certs.d/{{ fqdn }}"
    state: directory

- name: Download Web-Site SSL Certs
  get_url:
    url:  "https://{{ ca_ip }}/{{ fqdn }}/{{ fqdn }}.crt"
    dest: "/etc/docker/certs.d/{{ fqdn }}/{{ fqdn }}.cert"
    validate_certs: no
    mode: 0440
- get_url:
    url:  "https://{{ ca_ip }}/{{ fqdn }}/{{ fqdn }}.key"
    dest: "/etc/docker/certs.d/{{ fqdn }}/{{ fqdn }}.key"
    validate_certs: no
    mode: 0440
- get_url:
    url:  "https://{{ ca_ip }}/ca.pem"
    dest: "/etc/docker/certs.d/{{ fqdn }}/labo_local_ca.pem"
    validate_certs: no
    mode: 0440

- name: Download CA pem
  get_url:
    url:  "https://{{ ca_ip }}/ca.pem"
    dest: /etc/docker/certs.d/ca.pem
    validate_certs: no
    mode: 0440




######

- name: Re-Start dockerd
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: install docker-compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
