#
# mkdir directory for kubernetes
#

- name: mkdir for download
  file:
    path: "{{ work_dir }}"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: '0775'

- name: mkdir download
  file:
    path: "{{ download_dir }}"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0775'

- name: mkdir for admin
  file:
    path: "{{ cadmin_home }}"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: '0775'
