## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  "/home/{{ cluster_admin }}/.kube"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0755'

- name: copy config to home dir
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ cluster_admin }}/.kube/config"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'


- name: Remove admin.kubeconfig on NFS
  file:
    path: "{{ work_dir }}/kubeconfig/admin.kubeconfig_{{ cluster_name }}"
    state: absent

#
# この設定は、すこしおかしい！！！　修正が必要だ
#
- name: Copy admin.conf to NFS
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ work_dir }}/kubeconfig/admin.kubeconfig_{{ cluster_name }}"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'

