#
# crictlコマンドの接続先設定
#
- template:
    src: crictl.yaml
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: '0644'

#
# mkdir directory for cni
#  flannel などのプラグインの設定ファイルが入る
#
- name: start configuration
  file:
    path: /etc/cni/net.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: mkdir /opt/cni/bin/
  file:
    path: /opt/cni/bin/
    state: directory
    owner: root
    group: root
    mode: '0755'


- name: Configure CNI Networking
  unarchive:
    src: "{{ r_download_dir }}/cni-plugins-linux-amd64-{{ cni_plugins }}.tgz"
    dest: /opt/cni/bin/
    remote_src: True
    owner: root
    group: root
    mode: '0755'

  
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - nfs-common

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable


- name: Install docker-ce {{ docker_version }}
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce={{ docker_version }}
    - docker-ce-cli={{ docker_version }}
    - containerd.io
    
