#
# FLANNEL
#
# この部分は、net_flannelへ入れるべきじゃ？

#- debug: msg="{{ ansible_facts.hostname }}"

- name: Flannel Download 
  stat:
    path: "{{ download_dir }}/flannel-{{ flannel_version }}-linux-{{ cpu_arch }}.tar.gz"
  register: regi_flannel
  when: flannel_version is defined 

- get_url:
    url: https://github.com/coreos/flannel/releases/download/{{ flannel_version }}/flannel-{{ flannel_version }}-linux-{{ cpu_arch }}.tar.gz
    dest: "{{ download_dir }}"
    mode: '0644'
  when: flannel_version is defined and regi_flannel.stat.exists == False

- unarchive:
    src:  "{{ download_dir }}/flannel-{{ flannel_version }}-linux-{{ cpu_arch }}.tar.gz"
    dest: "{{ download_dir }}"
  when: flannel_version is defined 
