- copy:
    src: "{{ r_k8s_binary }}/kube-proxy"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'

- name: Configure the Kubernetes Proxy
  copy:
    src: "{{ r_ca_kubeconfig }}/kube-proxy.kubeconfig"
    dest: /etc/kubernetes/kube-proxy.conf
    owner: root
    group: root
    mode: '0644'
    remote_src: yes

- template:
    src: kube-proxy-config.yaml
    dest: /etc/kubernetes/config/
    owner: root
    group: root
    mode: '0644'

- template:
    src: kube-proxy.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- systemd:
    name: kube-proxy
    state: started
    daemon_reload: yes
    enabled: yes
