- name: Set node role
  shell: |
    #kubectl label node {{ item.name }} --overwrite=true node-role.kubernetes.io/controlplane=true
    #kubectl label node {{ item.name }} --overwrite=true node-role.kubernetes.io/etcd=true
    kubectl label node {{ item.name }} --overwrite=true node-role.kubernetes.io/master=""
    kubectl taint node {{ item.name }} --overwrite=true node-role.kubernetes.io/master="":NoSchedule
  args:
    chdir: "/home/{{ cluster_admin }}"
  when: item.name is match("master*")
  loop: "{{ nodes }}"    
  become: yes
  become_user: "{{ cluster_admin }}"

