- name: basic information
  hosts: all
  gather_facts: true
  become: true
  #
  vars:
    cluster_admin: ubuntu
    admin_user:    ubuntu
    mail_domain:   "labo.local"
    my_host:       "gitlab"
    fqdn:          "{{ my_host }}.labo.local"
    gitlab_data:   "/var/opt/gitlab"
    gitlab_bin:    "/opt/gitlab"
    dst_dir:       "/etc/gitlab/ssl"
    #disk_sdc:      "{{ my_data }}"

  #
  roles:
    - base_linux
    - docker
    - vdisks
    - download_certs
    - mail-client

  #
  tasks:
  - name: add repo for gitlab
    shell: |
      curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
    args:
      chdir: "{{ gitlab_data }}"


  - name: Install GitLab
    shell: |
      EXTERNAL_URL="https://gitlab.labo.local" apt-get install gitlab-ce
    args:
      chdir: "{{ gitlab_data }}"


  - name: GitLab password
    command: cat /etc/gitlab/initial_root_password
    register: gitlab_pw


  - debug: msg="initialAdminPassword = {{ gitlab_pw.stdout_lines }}"
