#
# エッジノード作成用プレイブック
#
# 利用方法
#  1. nodes の name と node_ipを編集する
#
#  2. 次のコマンドを実行する
#     ansible-playbook -i hosts_k8s playbook/create_kubeconfig_node.yaml
#
#  3. 上記の結果エッジノード作成のために以下の証明書が作成される。
#    /srv/k8s/ca/raspi92.pem
#    /srv/k8s/ca/raspi92-key.pem
#    /srv/k8s/kubeconfig/raspi92.kubeconfig
#
#  4. これを含めて必要な証明書等のファイルをエッジノードへ転送する
#    scp /srv/k8s/ca/ca.pem username@edgehost:
#    scp /srv/k8s/ca/raspi92.pem username@edgehost:
#    scp /srv/k8s/ca/raspi92-key.pem username@edgehost:
#    scp /srv/k8s/kubeconfig/raspi92.kubeconfig username@edgehost:
#    scp /srv/k8s/kubeconfig/kube-proxy.kubeconfig username@edgehost:
# 
#  5. 次にエッジノードの作業となる。
#    エッジノードにログインして、以下のコマンドを実行する
#      git clone https://github.com/takara9/rat-k8s
#      cd rat-k8s
#      sudo ansible-playbook -i hosts_edge playbook/install_edge.yaml
#
- name: Create kubeconfig for new nodes
  vars:
    nodes:
      - { name: 'raspi92' , node_ip: '192.168.1.244' }
  hosts:
  - bootnode
  roles:
    - create_kubeconfig

