# 
# マスターノードのセットアップ
#
- name: Configure etcd on masters
  hosts:
  - masters
  vars:
  - download_node: bootnode	
  gather_facts: yes
  become: yes
  roles:
    # ETCDのインストール
    #- etcd
    
    # ネットワークを設定 Calicoは別途導入
    #- role: net_bridge
    #  when: pod_network == "bridge"
    #- role: net_flannel
    #  when: pod_network == "flannel"
    
    # コンテナランタイムを選択してインストール
    - role: runtime_containerd
      when: container_runtime == "containerd" and pod_network != "bridge"
    #- role: runtime_docker
    #  when: container_runtime == "docker" and pod_network != "bridge"
    #- role: runtime_cri-o
    #  when: container_runtime == "cri-o" and pod_network != "bridge"

    # K8sマスターノードのモジュール導入
    #- node_master
    - node_master2
    
    # ブリッジ以外の時はK8sワーカーノードのモジュール導入
    #- role: node_worker
    #  when: pod_network == "flannel" or pod_network == "calico"

  tasks:
    # kubectlコマンドをログインシェルから使えるように設定する
    - include_tasks: tasks/kubeconfig_setup.yml

# 
#  RBAC の設定
#
- name: Configure RBAC
  hosts:
  - bootnode
  vars:
    - download_node: bootnode
  gather_facts: yes
  become: yes
  tasks:
    # 処理完了まで時間を取らないと失敗する
    # ネットワークやCPUの条件により調整する
    #- wait_for:
    #    timeout: 100
    # RBAC設定を追加
    #- include_tasks: tasks/config_rbac_kubelet.yml
    # kubectlコマンドをログインシェルから使えるように設定する      
    - include_tasks: tasks/kubeconfig_setup.yml

