- name: OS環境設定
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - base_linux

- name: Base configuration for all nodes
  hosts:
    - masters
    - nodes
  gather_facts: yes
  become: yes
  roles:
    - setup_kubeadm  # kubelet,kubeadm,kubectlのインストール
    #- bootnode	
    #- runtime_containerd
    - net_flannel
  tasks:
    - include_tasks: tasks/setup_k8s_dirs.yml



# 
# マスターノードのセットアップ
#
- name: Configure etcd on masters
  hosts:
  - masters
  gather_facts: yes
  become: yes
  roles:
    - node_master2
  tasks:
    - include_tasks: tasks/kubeconfig_setup.yml

#
# ワーカーノードのセットアップ
#
- name: Configure worker nodes
  hosts:
  - nodes
  - storages
  gather_facts: yes
  become: yes
  roles:
    - role: runtime_containerd
    - node_worker2








#
# masterクラスタのための内部LBの構築
#
#- name: Setup the internal LoadBalancer
#  hosts:
#  - mlb1
#  - mlb2
#  vars:
#  - lb_pos: "Internal"
#  gather_facts: yes
#  become: yes
#  roles:
#    - haproxy
#    - keepalived

#
# 外部リクエストをk8sクラスタ内へ導く外部LBを設定
#
#- name: Setup the external LoadBalancer
#  hosts:
#  - elb1
#  - elb2
#  vars:
#  - lb_pos: "Frontend"
#  gather_facts: yes
#  become: yes
#  roles:
#    - haproxy
#    - keepalived
#    - coredns_external
#    - loadbalancer_controller




#- name: Deploy addons
#  hosts: master1
#  gather_facts: yes
#  become: yes
#  roles:
#    #- addon_coredns  
#    - addon_helm3    
#    - addon_ingress
#    - addon_metrics-server
#    - addon_dashboard
