- name: OS環境設定
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    #- base_linux
    - linux-setup
- name: Base configuration for all nodes
  hosts:
    - masters
    - nodes
  gather_facts: yes
  become: yes
  roles:
    - runtime_containerd
    - setup_kubeadm  # kubelet,kubeadm,kubectlのインストール

#
# マスターノードのセットアップ
#
- name: Configure etcd on masters
  hosts:
  - masters
  gather_facts: yes
  become: yes
  roles:
    - node_master2
  tasks:
    - include_tasks: tasks/kubeconfig_setup.yml

#
# ワーカーノードのセットアップ
#
- name: Configure worker nodes
  hosts: nodes
  #gather_facts: yes
  become: yes
  roles:
    - node_worker2

- name: Configure Cluster Network
  hosts: master1
  #gather_facts: yes
  become: yes
  roles:
    - net_cilium    # 利用可能
  tasks:
    - include_vars:
        dir: vars
  #
  # ロードバランサーコントローラーが、ノードのロールを見ているので設定が必須
  #
    - name: Set node role
      become: true
      become_user: "{{ cluster_admin }}"
      shell: |
        kubectl label node {{ item.name }} --overwrite=true node-role.kubernetes.io/worker=''
        kubectl label node {{ item.name }} --overwrite=true role=worker-node
      args:
        chdir: "/home/{{ cluster_admin }}"
      loop: "{{ nodes }}"

#
# masterクラスタのための内部LBの構築
#
#- name: Setup the internal LoadBalancer
#  hosts:
#  - mlb1
#  - mlb2
#  vars:
#  - lb_pos: "Internal"
#  gather_facts: yes
#  become: yes
#  roles:
#    - haproxy
#    - keepalived

#
# 外部リクエストをk8sクラスタ内へ導く外部LBを設定
#
- name: Setup the external LoadBalancer
  hosts:
  - elb1
  - elb2
  vars:
  - lb_pos: "Frontend"
  gather_facts: yes
  become: yes
  roles:
    - haproxy
    - keepalived
    - coredns_external
    - loadbalancer_controller


- name: Deploy addons
  hosts: master1
  gather_facts: yes
  become: yes
  roles:
    #- addon_coredns
    - addon_helm3
    - addon_ingress
    - addon_metrics-server
    - addon_dashboard

