#
# 最小構成のK8sクラスタ
#
domain: labo.local
cluster_name: infra
os_variant:  ubuntu20.04

vm_spec:
  - name: "coredns"
    cpu: 2
    memory: 4096
    private_ip:  "172.16.0.8"
    public_ip:   "192.168.1.8"
    storage:
    - name: /dev/vdb
      size: 2
      vg:   vg1
    - name: /dev/vdc
      size: 2
      vg:   vg1
    - name: /dev/vdd
      size: 2
      vg:   vg1
    - name: /dev/vde
      size: 2
      vg:   vg1
    - name: /dev/vdf
      size: 2
      vg:   vg1
    playbook: install.yaml
    comment: "Name Server"

