#
# メールサーバー自動設定のタスク
#

- name: Setup postfix using debconf
  debconf:
    name: postfix
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: postfix/main_mailer_type, value: "Internet with smarthost", vtype: select }
    - { question: postfix/mailname, value: "{{ mail_domain }}", vtype: string }

- name: Install Postfix, mail command
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - postfix
      - mailutils



- name: Install Postfix, mail command
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - dovecot-core
      - dovecot-pop3d

- name: copy dovecot config files 10-auth.conf
  template:
    src:  10-auth.conf
    dest: /etc/dovecot/conf.d/10-auth.conf
    owner: root
    group: root
    mode:  '0644'


- name: copy dovecot config files 10-mail.conf
  template:
    src:  10-mail.conf
    dest: /etc/dovecot/conf.d/10-mail.conf
    owner: root
    group: root
    mode:  '0644'


- name: copy dovecot config files 10-master.conf
  template:
    src:  10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf
    owner: root
    group: root
    mode:  '0644'


- name: copy dovecot config files 10-ssl.conf
  template:
    src:  10-ssl.conf
    dest: /etc/dovecot/conf.d/10-ssl.conf
    owner: root
    group: root
    mode:  '0644'

#- name: copy dovecot users
#  template:
#    src:  users
#    dest: /etc/dovecot/users
#    owner: root
#    group: root
#    mode:  '0644'


- name: restart dovecot
  systemd:
    name: dovecot.service
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes


##
## Dovecot サンプルユーザー
##
- name: Add the user 'admin' 
  ansible.builtin.user:
    name: tkr
    shell: /bin/bash
    comment: Server Administrator
    groups: root
    append: yes
    state: present
    password: "{{ default_password | password_hash('sha512') }}"
    create_home: True

- name: Add the user 'tkr' 
  ansible.builtin.user:
    name: tkr
    shell: /bin/bash
    comment: Maho Takara	
    groups: users
    append: yes
    state: present
    password: "{{ default_password | password_hash('sha512') }}"
    create_home: True

- name: Add the user 'james' 
  ansible.builtin.user:
    name: james
    shell: /bin/bash
    groups: users
    append: yes
    state: present
    password: "{{ default_password | password_hash('sha512') }}"
    create_home: True
    