#
# CoreDNSのマニフェストをコピー
#
- name: Deploy CoreDNS
  template:
    src: coredns.yaml
    dest: "{{ cadmin_home }}/coredns.yaml"
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: 0644

#
# CoreDNSに登録するノードのIPアドレスリストをConfigMapへ登録
#  setup.rb による生成ファイル
#
- template:
    src: coredns-configmap.yaml
    dest: "{{ cadmin_home }}/coredns-configmap.yaml"
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: 0644

#
# CoreDNS のコンフィグマップ設定
#
- name: kubectl apply -f coredns-configmap.yaml
  shell: |
    kubectl apply -f coredns-configmap.yaml
  become_user: "{{ cluster_admin }}"
  become_method: sudo
  args:
    chdir: "{{ cadmin_home }}"
    executable: /bin/bash

#
# CoreDNSのデプロイ
#
- name: apply kubectl apply -f coredns.yaml
  shell: |
    kubectl apply -f coredns.yaml
  become_user: "{{ cluster_admin }}"
  become_method: sudo 
  args:
    chdir: "{{ cadmin_home }}"  
    executable: /bin/bash

