##
## コントロール・プレーン用
##  HA-PROXY
##
- debug: msg="{{ lb_pos }}"
- wait_for:
    timeout: 10
- name: check ping
  command: ping -c 3 192.168.1.1
  ignore_errors: yes

- wait_for:
    timeout: 10
- name: check ping
  command: ping -c 3 192.168.1.1
  ignore_errors: yes

- wait_for:
    timeout: 10
- name: check ping
  command: ping -c 3 192.168.1.1
  ignore_errors: yes

- name: Install the prerequisite packeage for HA-PROXY
  apt:
    name: "{{ packages }}"
    state: present
    #update_cache: yes
  register: apt_res
  retries: 10
  delay: 60
  until: apt_res is success
  vars:
    packages:
    - haproxy
    - haproxy-doc
    - haproxy-log-analysis
    - haproxyctl
    #- hatop 
  when:
    - ansible_facts.distribution == "Ubuntu"


- name: setup config
  template:
    src: haproxy_internal.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  when:
    - lb_pos == "Internal"

- name: setup config
  template:
    src: haproxy_frontend.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  when:
    - lb_pos == "Frontend"
    - front_proxy_vip_nomask is defined

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes

# 開発メモ
# 内部ロードバランサーと外部ロードバランサーを一つのplaybookで作成するのが
# 難しくなって来た。 次の改良では二つを分離しよう。

- name: stop haproxy
  systemd:
    name: haproxy
    state: stopped
    enabled: no
  when:
    - lb_pos == "Frontend"


- name: restart haproxy for Internal
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
  when:
    - lb_pos == "Internal"
 
