- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk1 }}"

- name: Create mount point
  file:
    path: "{{ fs_dns }}"
    owner: root
    group: root
    mode: '2775'
    state: directory

- name: Mount up device by {{ disk1 }}
  mount:
    path: "{{ fs_dns }}"
    src:  "{{ disk1 }}"
    fstype: ext4
    state: mounted



- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk2 }}"

- name: Create mount point
  file:
    path: "{{ fs_ca }}"
    owner: root
    group: root
    mode: '2775'
    state: directory
 
- name: Mount up device by {{ disk2 }}
  mount:
    path: "{{ fs_ca }}"
    src:  "{{ disk2 }}"
    fstype: ext4
    state: mounted



- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk3 }}"

- name: Create mount point
  file:
    path: "{{ fs_ldap }}"
    owner: root
    group: root
    mode: '2775'
    state: directory
    
- name: Mount up device by {{ disk3 }}
  mount:
    path: "{{ fs_ldap }}"
    src:  "{{ disk3 }}"
    fstype: ext4
    state: mounted



- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk4 }}"

- name: Create mount point
  file:
    path: "{{ fs_dex }}"
    owner: root
    group: root
    mode: '2775'
    state: directory
    
- name: Mount up device by {{ disk4 }}
  mount:
    path: "{{ fs_dex }}"
    src:  "{{ disk4 }}"
    fstype: ext4
    state: mounted



- name: mkfs ext4
  filesystem:
    fstype: ext4
    dev: "{{ disk5 }}"

- name: Create mount point
  file:
    path: "{{ fs_sso }}"
    owner: root
    group: root
    mode: '2775'
    state: directory
    
- name: Mount up device by {{ disk5 }}
  mount:
    path: "{{ fs_sso }}"
    src:  "{{ disk5 }}"
    fstype: ext4
    state: mounted

