---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi
stringData:
  # Key values correspond to a user name and its key, as defined in the
  # ceph cluster. User ID should have required access to the 'pool'
  # specified in the storage class
  userID: kubernetes
  userKey: AQDLZTBimW0dMhAAyFjpbOziw5IM/vLecnNPfA==
  # Encryption passphrase
  encryptionPassphrase: test_passphrase
