#
# プライベートCA証明書の取得
#
- name: Download CA pem
  get_url:
    url: "https://{{ ca_ip }}/ca.pem"
    dest: /etc/ssl/certs/labo_local_ca.pem
    validate_certs: no
    mode: 0440

- name: Download CA pem for Ubuntu 20.04 ca-certs
  get_url:
    url: "https://{{ ca_ip }}/ca.pem"
    dest: /usr/share/ca-certificates/labo_local_ca.crt
    validate_certs: no
    mode: 0440

- name: Execute update-ca-certificates
  shell: |
    echo "labo_local_ca.crt" >> /etc/ca-certificates.conf
    update-ca-certificates

#
# ウェブサイト用の証明書の取得
#
- name: mkdir dest dir
  file:
    path: "{{ dst_dir }}"
    state: directory

- name: Download Web-Site SSL Certs
  get_url:
    url:  "https://{{ ca_ip }}/{{ fqdn }}/{{ fqdn }}.crt"
    dest: "{{ dst_dir }}/{{ fqdn }}.crt"
    validate_certs: no
    mode: 0440
- get_url:
    url:  "https://{{ ca_ip }}/{{ fqdn }}/{{ fqdn }}.key"
    dest: "{{ dst_dir }}/{{ fqdn }}.key"
    validate_certs: no
    mode: 0440


#
# Vagrant用の設定　既に不要？
#
#- debug: msg="virtualization_type = {{ ansible_facts.virtualization_type }}"
#- shell: |
#    cp {{ domain }}.cert /vagrant/{{ domain }}.cert
#    cp {{ domain }}.key  /vagrant/{{ domain }}.key
#    cp ca.crt /vagrant/ca.crt
#  args:
#    chdir: "{{ ca_dir }}"
#  when: ansible_facts.virtualization_type == "virtualbox"

