apiVersion: apps/v1
kind: Deployment
metadata:
  name: boostable-mysql
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
    spec:
      nodeName: node2
      containers:
      - name: mysql    
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: hello
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
