## kubeconfigディレクトリ作成

- name: mkdir kubeconfig
  file:
    path:  "/home/{{ cluster_admin }}/.kube"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0755'

- name: copy config to home dir
  copy:
    src: "{{ ca_kubeconfig }}/admin.kubeconfig_{{ cluster_name }}"
    dest: "/home/{{ cluster_admin }}/.kube/config"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'

- name: admin.kubeconfig をNFSへ保存
  copy:
    src: "{{ ca_kubeconfig }}/admin.kubeconfig_{{ cluster_name }}"
    dest: "{{ ca_kubeconfig }}"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'

