## kubeconfigディレクトリ作成
#
- name: mkdir kubeconfig
  file:
    path:  "/root/.kube"
    state: directory
    owner: "root"
    group: "root"
    mode:  '0755'

- name: copy config to home dir
  copy:
    src: "{{ r_ca_kubeconfig }}/admin.kubeconfig"
    dest: "/root/.kube/config"
    remote_src: yes    
    owner: "root"
    group: "root"
    mode:  '0600'



