#
# 自動設定のタスクを記述する。
#
- name: Setup postfix using debconf
  debconf:
    name: postfix
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: postfix/main_mailer_type, value: "Satellite system", vtype: select }
    - { question: postfix/mailname, value: "{{ ansible_facts.hostname }}.{{ mail_domain }}", vtype: string }
    - { question: postfix/relayhost, value: "mail.{{ mail_domain }}", vtype: string }

- name: Install Ubuntu package
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - postfix    
      - mailutils



- name: Edit postfix main.cf
  replace:
    path: /etc/postfix/main.cf
    regexp: '^myhostname = localhost'
    replace: "myhostname = {{ ansible_facts.hostname }}"

- systemd:
    name: postfix
    state: restarted
    daemon_reload: yes
    enabled: yes
