#
# CRI
#
- name: Downloading cri-containerd
  stat:
    path: "{{ download_dir }}/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
  #when: ansible_facts.hostname is match(download_node) and containerd_version is version('1.3.4', '<')
  when: containerd_version is version('1.3.4', '<')
  register: regi_cri_containerd
  
- get_url:
    url: "https://storage.googleapis.com/cri-containerd-release/cri-containerd-{{ containerd_version }}.linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - containerd_version is version('1.3.4', '<')
    - regi_cri_containerd.stat.exists == False



#
# CRI ver 1.3以上
#
- name: Downloading cri-containerd
  stat:
    path: "{{ download_dir }}/cri-containerd-cni-{{ containerd_version }}-linux-amd64.tar.gz"
  #when: ansible_facts.hostname is match(download_node) and containerd_version is version('1.3.4', '>')
  when: containerd_version is version('1.3.4', '>')
  register: regi_cri_containerd

- get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{ containerd_version }}/cri-containerd-cni-{{ containerd_version }}-linux-amd64.tar.gz"
    dest: "{{ download_dir }}"
    mode: '0644'
  when:
    - containerd_version is version('1.3.4', '>')
    - regi_cri_containerd.stat.exists == False



