- name: mkdir .ssh directory
  file:
    path: "/root/.ssh"
    state: directory
    owner: root
    group: root
    mode: '0700'
- name: Copy shared_fs keys to id_rsa.pub
  command: cp "{{ r_work_dir }}/keys/id_rsa.pub" /root/.ssh/id_rsa.pub 
- file:
    path: /root/.ssh/id_rsa.pub 
    owner: root
    group: root
    mode: '0644'
- name: Copy shared_fs/keys to id_rsa 
  command: cp "{{ r_work_dir }}/keys/id_rsa" /root/.ssh/id_rsa 
- file:
    path: /root/.ssh/id_rsa 
    owner: root
    group: root
    mode: '0600'

- name: Create authorized_keys
  command: cp "{{ r_work_dir }}/keys/id_rsa.pub"  /root/.ssh/authorized_keys
- file:
    path: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: '0400'
