---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: cephfs
  userKey: AQA7yg9kixu1IhAAqJV9wyesJR+ZEso7/7sTDA==

  # Required for dynamically provisioned volumes
  adminID: cephfs
  adminKey: AQA7yg9kixu1IhAAqJV9wyesJR+ZEso7/7sTDA==
