- debug: msg="{{ ansible_facts.hostname }}"

- name: check istio
  stat:
    path: "{{ cadmin_home }}/istio-{{ istio_version }}/README.md"
  register: file_istio

#
# istioctrl のインストール
#
- name: install Istio step-1
  become_user: "{{ cluster_admin }}"
  shell: |
    curl -L https://istio.io/downloadIstio | ISTIO_VERSION={{ istio_version }} TARGET_ARCH=x86_64 sh -
  args:
    chdir: "{{ cadmin_home }}"
  when: file_istio.stat.exists == False

#
# istioctl は bootnode の /usr/local/bin へ配置する
#
- name: deploy istioctl to /usr/local/bin
  copy:
    src: "{{ cadmin_home }}/istio-{{ istio_version }}/bin/istioctl"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'


#
# ローカルゲートウェイを追加
#
- name: add cluster-local-gateway
  template:
    src: istio-cluster-local-gateway.yaml
    dest: "{{ cadmin_home }}/istio-{{ istio_version }}/istio-cluster-local-gateway.yaml"
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode: '0644'

#
# Istioのインストール
#
- name: install Istio step-2
  become_user: "{{ cluster_admin }}"
  shell: |
    export PATH=$PWD/bin:$PATH
    istioctl install -y --set profile=default -f istio-cluster-local-gateway.yaml
  args:
    chdir: "{{ cadmin_home }}/istio-{{ istio_version }}"

# ロードバランサーを使用するので不要
# Istio パッチを適用する、NodePortとして公開するため。
#
#- template:
#    src: istio-patch.yaml
#    dest: "{{ cadmin_home }}/istio-patch.yaml"
#    owner: "{{ cluster_admin }}"
#    group: "{{ cluster_admin }}"
#    mode: '0644'
#    
#- name: apply patch for Istio
#  become_user: "{{ cluster_admin }}"
#  shell: |
#    kubectl patch svc istio-ingressgateway --patch "$(cat istio-patch.yaml)" -n istio-system
#  args:
#    chdir: "{{ cadmin_home }}"
#




##
## 名前空間 default のインジェクションを明示的に禁止する
##
- name: Disable istio-injection at default namespace
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl label namespace default istio-injection=disabled --overwrite=true
  args:
    chdir: "{{ cadmin_home }}/"

##
## Istio Gateway 用の証明書作成
##
- name: Create Secret for TLS
  include_tasks: tls.yaml
    
    
##
## Kiali, Jeager のインストールと公開
## 
- name: Deploy prometheus.yaml
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl apply -f prometheus.yaml
  args:
    chdir: "{{ cadmin_home }}/istio-{{ istio_version }}/samples/addons/"

- name: Deploy grafana.yaml
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl apply -f grafana.yaml
  args:
    chdir: "{{ cadmin_home }}/istio-{{ istio_version }}/samples/addons/"

- name: Deploy jaeger.yaml
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl apply -f jaeger.yaml
    kubectl patch svc tracing -n istio-system -p '{"spec":{"type":"NodePort","ports":[{"name": "http","port": 80,"nodePort": 32095}]}}'    
  args:
    chdir: "{{ cadmin_home }}/istio-{{ istio_version }}/samples/addons/"

- name: Deploy kiali.yaml
  become_user: "{{ cluster_admin }}"
  shell: |
    kubectl apply -f kiali.yaml
    sleep 60
    kubectl apply -f kiali.yaml
    kubectl patch svc kiali -n istio-system -p '{"spec":{"type":"NodePort","ports":[{"name": "http","port": 20001,"nodePort": 32001},{"port":9090, "nodePort":32090}]}}'
  args:
    chdir: "{{ cadmin_home }}/istio-{{ istio_version }}/samples/addons/"


    
    
  
