###############################
- name: Configure worker node
  file:
    path: /var/lib/kubelet
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /var/lib/kube-proxy
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /etc/kubernetes/config
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode: '0755'

- file:
    path: /var/run/kubernetes
    state: directory
    owner: root
    group: root
    mode: '0755'
- file:
    path: /etc/kubelet.d
    state: directory
    owner: root
    group: root
    mode: '0755'
