#
# CNI-PLUGIN
#
- name: Downloading cni-plugins
  stat:
    path: "{{ download_dir }}/cni-plugins-linux-{{ cpu_arch }}-{{ cni_plugins }}.tgz"
  register: regi_cni

- get_url:
    url: https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins }}/cni-plugins-linux-{{ cpu_arch }}-{{ cni_plugins }}.tgz
    dest: "{{ download_dir }}"
    mode: '0644'
  when: regi_cni.stat.exists == False
      

