- name: copy kubectl 
  copy:
    src: "{{ download_dir }}/kubernetes/server/bin/kubectl"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    #remote_src: yes

- name: copy kubelet
  copy:
    src: "{{ download_dir }}/kubernetes/server/bin/kubelet"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    #remote_src: yes

- name: copy kube-proxy
  copy:
    src: "{{ download_dir }}/kubernetes/server/bin/kube-proxy"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: '0755'
    #remote_src: yes

