- debug: msg="{{ ansible_facts.hostname }}"
- include_tasks: mkdir_for_download.yaml
- include_tasks: dl_cni_plugin.yaml
#- include_tasks: dl_containerd.yaml
- include_tasks: dl_addon_flannel.yaml
#- include_tasks: dl_cri_containerd.yaml
- include_tasks: install_docker_ce.yaml
- include_tasks: dl_crictl.yaml
#- include_tasks: dl_runc.yaml
- include_tasks: dl_k8s_bin.yaml
- include_tasks: install_kube_bin.yaml

## ワーカーノードのディレクトリ作成
- name: setup directory for worker node
  include_tasks: create_dir_worker.yaml
## Containerd のセットアップ
#- name: Install Containerd
#  include_tasks: containerd.yaml
## kube-proxy インストール
- name: Install kube-proxy
  include_tasks: kube-proxy.yaml
## kubelet インストール
- name: Install kubelet
  include_tasks: kubelet.yaml

